#!/usr/bin/env python3
"""Build the static RAPPterverse Data catalog site without dependencies."""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def load_json(path: Path) -> dict:
    with path.open(encoding="utf-8") as stream:
        value = json.load(stream)
    if not isinstance(value, dict):
        raise ValueError(f"{path}: root must be an object")
    return value


def dataset_rows(catalog: dict) -> str:
    rows = []
    for dataset in sorted(catalog.get("datasets", []), key=lambda item: item["id"]):
        dataset_id = html.escape(str(dataset["id"]), quote=True)
        title = html.escape(str(dataset.get("title", dataset_id)))
        version = html.escape(str(dataset.get("version", "unreleased")))
        records = int(dataset.get("records", 0))
        manifest = html.escape(str(dataset.get("manifest", "")), quote=True)
        link = (
            f'<a href="../{manifest}">manifest</a>'
            if manifest
            else '<span class="muted">pending</span>'
        )
        rows.append(
            "<tr>"
            f"<td><code>{dataset_id}</code></td>"
            f"<td>{title}</td>"
            f"<td>{version}</td>"
            f"<td>{records:,}</td>"
            f"<td>{link}</td>"
            "</tr>"
        )
    if not rows:
        return '<tr><td colspan="5" class="muted">No public releases yet.</td></tr>'
    return "\n".join(rows)


def render(catalog: dict, latest: dict) -> str:
    release = html.escape(str(latest.get("release") or "none"))
    manifest_hash = html.escape(str(latest.get("manifestSha256") or "pending"))
    rows = dataset_rows(catalog)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Open, replayable datasets generated by the RAPPterverse">
  <title>RAPPterverse Data</title>
  <style>
    :root {{ color-scheme: dark; font-family: ui-monospace, SFMono-Regular, Consolas, monospace; }}
    body {{ margin: 0; background: #070b14; color: #dce7ff; }}
    main {{ max-width: 1100px; margin: auto; padding: 4rem 1.5rem; }}
    h1 {{ color: #55e6ff; letter-spacing: .08em; }}
    .card {{ background: #101827; border: 1px solid #24344f; border-radius: 12px; padding: 1rem 1.25rem; margin: 1rem 0; }}
    table {{ width: 100%; border-collapse: collapse; }}
    th, td {{ text-align: left; padding: .75rem; border-bottom: 1px solid #24344f; }}
    th {{ color: #f0c45a; }}
    a {{ color: #55e6ff; }}
    .muted {{ color: #8491a7; }}
    code {{ overflow-wrap: anywhere; }}
  </style>
</head>
<body>
<main>
  <h1>RAPPTERVERSE DATA</h1>
  <p>Open, replayable synthetic datasets and deterministic world-pack sources.</p>
  <section class="card">
    <strong>Latest release:</strong> {release}<br>
    <strong>Manifest SHA-256:</strong> <code>{manifest_hash}</code>
  </section>
  <section class="card">
    <h2>Datasets</h2>
    <table>
      <thead><tr><th>ID</th><th>Dataset</th><th>Version</th><th>Records</th><th>Data</th></tr></thead>
      <tbody>{rows}</tbody>
    </table>
  </section>
  <p class="muted">Only reviewed, content-addressed artifacts are published here.</p>
</main>
</body>
</html>
"""


def build(output: Path) -> dict:
    catalog = load_json(ROOT / "catalog" / "catalog.json")
    latest = load_json(ROOT / "catalog" / "latest.json")
    if output.exists():
        shutil.rmtree(output)
    (output / "catalog").mkdir(parents=True)
    index = render(catalog, latest)
    (output / "index.html").write_text(index, encoding="utf-8")
    (output / ".nojekyll").write_text("", encoding="utf-8")
    for name in ("catalog.json", "latest.json"):
        shutil.copy2(ROOT / "catalog" / name, output / "catalog" / name)
    return {
        "files": 4,
        "indexSha256": hashlib.sha256(index.encode("utf-8")).hexdigest(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "_site")
    args = parser.parse_args()
    print(json.dumps(build(args.output.resolve()), sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
